name: Build and Push to ACR (personal creds)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure CLI using username/password
        run: |
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: |
          az acr login --name myacrhosni

      - name: Build Docker image
        run: docker build -t myacrhosni.azurecr.io/myapp_backend:v1 .

      - name: Push to ACR
        run: docker push myacrhosni.azurecr.io/myapp_backend:v1
